# Generated by Django 4.1.4 on 2022-12-21 08:53

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, null=True)),
                (
                    "contact_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, unique=True
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("G", "Gsec"),
                            ("H", "Hall President"),
                            ("W", "Warden"),
                        ],
                        default=None,
                        max_length=1,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "room_no",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("block_no", models.CharField(max_length=1, null=True)),
                ("capacity", models.IntegerField(default=1)),
                ("vacancy", models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                ("name", models.CharField(max_length=200, null=True)),
                (
                    "roll_no",
                    models.CharField(
                        max_length=10, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "contact_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, unique=True
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hostel.room",
                    ),
                ),
            ],
        ),
    ]
