# Generated by Django 4.1.4 on 2022-12-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hostel", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="room", name="block_no",),
        migrations.AddField(
            model_name="room",
            name="block_name",
            field=models.CharField(
                choices=[
                    ("A", "A-block"),
                    ("B", "B-block"),
                    ("C", "C-block"),
                    ("D", "D-block"),
                    ("E", "E-block"),
                ],
                default=None,
                max_length=1,
                null=True,
            ),
        ),
    ]
